app_id: E74DE52E-9367-42FA-A15C-FF0EE4F5E071
publisher: 夏沫花火zzz
publisher_url: https://1l1.icu
display_name: Nya LoCyanFrp!
create_desktop_icon: true
install_dir_name: NyaLCF
script_template: inno_setup.iss
locales:
  - zh