app_id: E74DE52E-9367-42FA-A15C-FF0EE4F5E071
publisher: Muska-Ami
publisher_url: https://blog.1l1.icu
display_name: Nya LoCyanFrp!
create_desktop_icon: true
install_dir_name: NyaLCF
locales:
  - en
  - zh